version : '3'

services:
    database:
        image: 'mongo'
        container_name: mongo_db
        networks:
            - backend
    app:
        build: .
        container_name: node_container
        networks:
            - backend
        volumes:
            - ./:/root/app
            - /root/app/node_modules
        ports:
            - 8080:8080

networks:
    backend:
